# Supabase PostgreSQL Bağlantısı
spring.datasource.url=jdbc:postgresql://eykakqrvaofqelodwkdu.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=FlOv21BiT.21
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Ayarları
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true